language: generic

services:
  - docker

script:
  # chains
  - ./images/build-fullnode-btcd.sh
  - ./images/fullnode/build-parity.sh
  # markets
  - ./images/build-markets.sh

before_deploy:
  - ./images/run-fullnode-btcd.sh --version

cache:
  # parity
  - cargo
