language: generic

services:
  - docker

script:
  # chains
  - ./images/build-fullnode-btcd.sh
  # [ ] speed up builds for markets testing
  #- ./images/fullnode/build-parity.sh
  # markets
  - ./images/build-markets.sh

# parity
cache: cargo
