# Source configuration
# https://github.com/cyberFund/cyber-markets/blob/development/devops/local-elassandra/docker-compose.yml
#
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chainvisor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: storage
        app: elassandra
    spec:
      volumes:
      - name: elassandra-db-volume
        # [ ] make it persistent even when Pod dies
        #persistentVolumeClaim:
        #  claimName: elassandra-pv-claim
        emptyDir: {}
      containers:
      - name: elassandra
        image: strapdata/elassandra:2.4.5.5
        env:
        - name: CASSANDRA_DC
          value: PRODUCTION
        - name: CASSANDRA_CLUSTER_NAME
          value: CYBERNODE
        ports:
        #    9042: CQL
        #    9200: ElasticSearch HTTP
        - containerPort: 9042
        - containerPort: 9200
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: elassandra-db-volume
---
apiVersion: v1
kind: Service
metadata:
  name: elassandra
spec:
  ports:
  - port: 9042
    name: cql
  - port: 9200
    name: elastic
  selector:
    app: elassandra

